export const STAGES = {
  "MAIN STAGE": {
    fri: ["MAJOR LAZER", "ALESSO B2B MARTIN GARRIX", "BZRP", "ILLENIUM", "WORSHIP", "VOYD", "FRANK WALKER"],
    sat: ["SEBASTIAN INGROSSO B2B STEVE ANGELLO", "ARMIN VAN BUUREN", "HARDWELL", "EXCISION", "STEVE AOKI", "ALAN WALKER", "LOUD LUXURY", "NICKY ROMERO", "HALO", "MYKRIS", "GIL GLAZE"],
    sun: ["JOHN SUMMIT", "DJ SNAKE", "AFROJACK", "MARLON HOFFSTADT", "ARTBAT", "MADDIX", "R3HAB", "ME N Ü", "KAPUCHON"],
  },
  "WORLDWIDE": {
    fri: ["ARMIN VAN BUUREN", "ARMIN VAN BUUREN B2B MARLON HOFFSTADT", "LILLY PALMER", "VINI VICI", "SUPERSTRINGS", "MATTY RALPH", "PRADA2000"],
    sat: ["ISOXO", "YOUSUKE YUKIMATSU", "HAMDI", "OUTLAW B2B TRYM", "KAI WACHI", "BOU", "HOLI", "ARMHMR", "DANIEL ALLAN", "SIDEQUEST", "DISTINCT MOTIVE", "JULIAN CROSS"],
    sun: ["WANKDAT", "RAY VOLPE B2B SULLIVAN KING", "PEEKABOO", "HOLY PRIEST", "ANDY C", "LAYZ", "BOLO", "GORILLAT", "BIG FLORIDA"],
  },
  "MEGASTRUCTURE": {
    fri: ["ERIC PRYDZ", "VINTAGE CULTURE", "MISS MONIQUE", "MASSANO", "MAR-T"],
    sat: ["CARL COX", "ADAM BEYER B2B JOSEPH CAPRIATI", "ELI BROWN", "SASHA_JOHN DIGWEED", "ALAN FITZPATRICK B2B MARCO FARAONE", "JULIET FOX", "ANDY PATE B2B ROD B."],
    sun: ["AMELIE LENS B2B SARA LANDRY", "BORIS BREJCHA", "ADRIATIQUE", "ARGY B2B MILO HÁJSEIT", "SCENARIOS", "BASSETT B2B CHRISTOPHER", "JAMES"],
  },
  "THE COVE": {
    fri: ["SARA LANDRY", "CLARA CUVE", "999999999", "ALTB", "GODTRIPPER"],
    sat: ["JORIS VOORN B2B KOROLOVA", "CASSIAN", "COLYN B2B INNELLEA", "DEEP DISH", "KASIA", "RIVO", "OLYMPE", "JOA"],
    sun: ["THE MARTINEZ BROTHERS", "DENNIS CRUZ B2B SETH TROXLER", "ROSSI.", "MALONE", "BLACK FANCY", "PLASTIK FUNK", "M.O.N.R.O.E."],
  },
  "LIVE": {
    fri: ["LEVITY", "OF THE TREES", "BTSM", "SHIMA", "AFROBETA"],
    sat: ["BRUTALISMUS 3000", "BOYS NOIZE LIVE", "MADEON", "SNOW STRIPPERS", "CONFIDENCE MAN", "MISS BASHFUL"],
    sun: ["ZHU", "TIM3LESS", "LOUIS THE CHILD", "PARISI", "BOIISH"],
  },
  "RADIO": {
    fri: ["BLOODY BEETROOTS", "RIOT TEN", "LAIDBACK LUKE", "***** B2B *****", "STEVE AOKI", "JESSICA AUDIFFRED", "NOSTALGIX", "OOKAY", "LINNEY"],
    sat: ["SOREN", "D-STURB", "DUAL DAMAGE", "MISH", "DA TWEEKAZ", "COONE", "THE SAINTS", "THE PURGE", "AUDIOFREQ", "DARKSIDERZ", "KREATION"],
    sun: ["PETERBLUE", "DJ GIGOLA", "MCR-T", "FIXNERS", "X CLUB", "FROST CHILDREN", "EERA"],
  },
  "OASIS": {
    fri: ["LUCA TESTA", "ADAM DE GREAT", "DJ HANNAH", "TAK SHAK", "LOS DE LA VEGA", "RICHARD FRAIOLI B2B JIMMIE PAGE B2B DJ IDEAL", "MIND.E", "NUDOS"],
    sat: ["WALLY LOPEZ", "ALEXANDER SOM", "MARCO NINNI", "PINTO", "JACK VICE", "LUCY GUO", "BILL KELLY", "OMAR DEAZ", "SOUL GOODMAN B2B DABURA", "KAORU", "JUNO B2B WYZZARD B2B BEBE BREAKS", "CIMEO"],
    sun: ["METAPHYSICAL", "X-CON B2B MARVIN DELGADO B2B CJ", "PURPLE", "LUKE HUNTER", "AUDIOSAL", "WAGS B2B LEMONY SNICKETTS", "SEBASTIAN MORXX", "RODRIGO VIEIRA", "ANDY ARES", "CVMRN", "DUBPLATES & DRAGONS"],
  },
};

export const DAYS = ["fri", "sat", "sun"];
export const DAY_LABELS = { fri: "FRI 3/27", sat: "SAT 3/28", sun: "SUN 3/29" };
export const DAY_FULL = { fri: "FRIDAY", sat: "SATURDAY", sun: "SUNDAY" };
export const STAGE_NAMES = Object.keys(STAGES);
export const COLORS = ["#F97316","#06B6D4","#A855F7","#F43F5E","#22C55E","#EAB308","#EC4899","#3B82F6","#14B8A6","#F59E0B","#8B5CF6","#10B981"];
